---
version: "3"

services:
  indexer:
    image: postgres
    restart: always
    volumes:
      - postgre-volume:/var/lib/postgresql/data

  storage:
    image: redis
    restart: always

  gnocchi-metricd:
    image: gnocchi
    restart: always
    environment:
      POSTGRESQL_USER: postgres
    build:
      context: gnocchi
      args:
        package_name: "${GNOCCHI_PACKAGE_NAME:-gnocchi}"
    depends_on:
      - indexer
      - storage
    volumes:
      - metrics-volume:/var/lib/gnocchi
    entrypoint: /run-gnocchi.sh metricd

  gnocchi-api-uwsgi:
    image: gnocchi
    restart: always
    environment:
      POSTGRESQL_USER: postgres
    build:
      context: gnocchi
      args:
        package_name: "${GNOCCHI_PACKAGE_NAME:-gnocchi}"
    depends_on:
      - indexer
      - storage
      - gnocchi-metricd
    volumes:
      - metrics-volume:/var/lib/gnocchi
    entrypoint: /run-gnocchi.sh api

  grafana:
    image: gnocchixyz/grafana
    restart: always
    build:
      context: grafana
    environment:
      - GNOCCHI_RATE_SUPPORT
      - GRAFANA_PLUGIN_URL
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_GNOCCHI_ENDPOINT=http://gnocchi:8041
    ports:
      - "3000:3000"
    depends_on:
      - gnocchi-api-nginx
    volumes:
      - grafana-volume:/var/lib/grafana
    links:
      - "gnocchi-api-nginx:gnocchi"

  gnocchi-api-nginx:
    image: nginx
    restart: always
    volumes:
      - ./gnocchi/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - metrics-volume:/var/lib/gnocchi
    depends_on:
      - gnocchi-api-uwsgi
    ports:
      - 8041:8041

  influx-listener-openhab:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf-openhab.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - gnocchi-api-nginx
    ports:
      - 8086:8086
    links:
      - "gnocchi-api-nginx:gnocchi"

volumes:
  metrics-volume:
  grafana-volume:
  postgre-volume:
